Extension to sort filter values
shopgate-professional-services/ext-sort-filters pull request #1
Opened 2020-11-26 13:30 UTC by alexbridge

Extension to sort filter values

2020-11-26 14:22 UTC, Carsten89 requested changes

2020-11-26 14:22 UTC, Carsten89 commented on README.md
> +Sorting filters and filters values for search and category pages.
```suggestion
Sorting filters and filter values for search and category pages.
```

2020-11-26 14:22 UTC, Carsten89 commented on extension-config.json
> +        "type": "json" ,
```suggestion
        "type": "checkbox" ,
```

2020-11-26 14:22 UTC, Carsten89 commented on extension-config.json
> +        "display_amount": -10,
remove defaults

2020-11-26 14:22 UTC, Carsten89 commented on extension-config.json
> +        "type": "json" ,
```suggestion
        "type": "checkbox" ,
```

2020-11-26 14:22 UTC, Carsten89 commented on extension/sortValues.js
> +      if (filter.type !== 'multiselect') {
why do we only handle type multiselect here. what about singleselect for example and potentials others?

2020-11-27 12:19 UTC, alexbridge commented on extension/sortValues.js
> +      if (filter.type !== 'multiselect') {
The others are `range` . And values can be only in multiselect

2020-11-27 16:35 UTC, Carsten89 commented on extension/sortValues.js
> +      if (filter.type !== 'multiselect') {
```suggestion
      if (filter.type === 'range') {
```
?

2020-11-27 16:43 UTC, Carsten89 approved these changes

2020-11-30 07:12 UTC, merged